apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecms
  namespace: ecms
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ecms.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ecms-backend
                port:
                  number: 80
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: ecms-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecms-frontend
                port:
                  number: 80
