"""Golden exemplar — an approved reference org chart.

Embedded in the design-team prompt as the calibration example the model imitates:
the structure, role mix, delegation shape, and depth of a real software-services
delivery org. Content changes per project; this SHAPE does not. Note the
asymmetry — some branches have a lead + engineers, others are a single IC
reporting straight to the engineering manager. Depth is sized to the work.
"""

from __future__ import annotations

# The approved team shape (the Adrenaline -> Frappe HR migration scenario).
GOLDEN_TEAM = {
    "agents": [
        {
            "key": "delivery-manager",
            "name": "Delivery Manager",
            "designation": "Engagement Delivery Manager",
            "role": "delivery_manager",
            "department": "backend",
            "reports_to": None,
            "goal": "Own the client outcome, phase gates, and sign-off for the HR migration.",
            "instructions": "Drive the 3-phase rollout. Enforce phase gates: data migration, then sync, then mobile. Escalate blockers and secure client approval before each cutover.",
            "skills": ["delivery management", "stakeholder management", "risk management"],
            "model": "gpt-4o",
            "tools": ["assign_task", "my_tasks", "search_org", "search_memory"],
        },
        {
            "key": "solution-architect",
            "name": "Solution Architect",
            "designation": "Migration Solution Architect",
            "role": "architect",
            "department": "backend",
            "reports_to": "delivery-manager",
            "goal": "Own the migration architecture and review all technical decisions.",
            "instructions": "Define the Adrenaline->Frappe mapping strategy, sync topology, and cutover design. Review pod output against SOC2 and data-residency constraints.",
            "skills": ["system design", "Frappe/ERPNext", "data architecture"],
            "model": "gpt-4o",
            "tools": ["read_file", "search_code", "search_memory", "query_graph"],
        },
        {
            "key": "business-analyst",
            "name": "Business Analyst",
            "designation": "Requirements Custodian",
            "role": "business_analyst",
            "department": "documentation",
            "reports_to": "delivery-manager",
            "goal": "Hold requirements custody and acceptance criteria throughout delivery.",
            "instructions": "Keep the finalized requirements authoritative. Translate client answers into acceptance criteria for each pod.",
            "skills": ["requirements elicitation", "acceptance criteria"],
            "model": "gpt-4o",
            "tools": ["read_file", "search_memory", "note"],
        },
        {
            "key": "engineering-manager",
            "name": "Engineering Manager",
            "designation": "Engineering Manager",
            "role": "engineering_manager",
            "department": "backend",
            "reports_to": "delivery-manager",
            "goal": "Run the engineering pods and assign delivery work.",
            "instructions": "Break the architecture into pod-level tasks. Assign work to leads and ICs and unblock them.",
            "skills": ["engineering management", "planning"],
            "model": "gpt-4o",
            "tools": ["assign_task", "my_tasks", "search_code", "read_file"],
        },
        {
            "key": "data-migration-lead",
            "name": "Data Migration Lead",
            "designation": "Senior Data Engineer (Lead)",
            "role": "tech_lead",
            "department": "data_migration",
            "reports_to": "engineering-manager",
            "goal": "Lead migration of 450 Adrenaline tables to Frappe DocTypes with zero data loss.",
            "instructions": "Own the mapping catalog. Use Employee ID as the canonical key. Reconcile every batch against source counts.",
            "skills": ["MySQL", "Frappe DocTypes", "ETL"],
            "model": "gpt-4o",
            "tools": ["assign_task", "read_file", "edit_file", "search_code"],
        },
        {
            "key": "data-migration-engineer",
            "name": "Data Migration Engineer",
            "designation": "Data Engineer",
            "role": "engineer",
            "department": "data_migration",
            "reports_to": "data-migration-lead",
            "goal": "Implement and validate the table-to-DocType field mappings.",
            "instructions": "Map custom Adrenaline fields to Frappe custom fields. Write validators for every mapping and log mismatches.",
            "skills": ["MySQL", "Python", "data validation"],
            "model": "claude-3.5-sonnet",
            "tools": ["read_file", "edit_file", "search_code", "grep", "shell_command"],
        },
        {
            "key": "integration-engineer",
            "name": "Integration Engineer",
            "designation": "Real-time Sync Engineer",
            "role": "engineer",
            "department": "integration",
            "reports_to": "engineering-manager",
            "goal": "Achieve <2s bidirectional MySQL<->Frappe HR sync via GCP Pub/Sub.",
            "instructions": "Implement idempotent writes with a dead-letter queue. Frappe wins on HR fields, MySQL on transaction fields.",
            "skills": ["GCP Pub/Sub", "real-time sync", "MySQL replication"],
            "model": "claude-3.5-sonnet",
            "tools": ["read_file", "edit_file", "write_file", "search_code", "shell_command"],
        },
        {
            "key": "sre",
            "name": "DevOps / SRE",
            "designation": "Site Reliability Engineer",
            "role": "sre",
            "department": "infrastructure",
            "reports_to": "engineering-manager",
            "goal": "Provision and operate the Frappe HR stack on GCP.",
            "instructions": "Stand up GKE, managed MySQL, and Pub/Sub via IaC. Set up monitoring and rollback runbooks for each phase.",
            "skills": ["GCP", "Terraform", "GKE", "observability"],
            "model": "gpt-4o",
            "tools": ["shell_command", "read_file", "edit_file", "monitor_command"],
        },
        {
            "key": "security-engineer",
            "name": "Security Engineer",
            "designation": "Security & Compliance Engineer",
            "role": "security_engineer",
            "department": "security",
            "reports_to": "engineering-manager",
            "goal": "Enforce PII encryption, RBAC, and data-residency compliance.",
            "instructions": "Verify AES-256 at rest and TLS 1.3 in transit. Audit RBAC on migration mappings. Confirm data residency.",
            "skills": ["security", "RBAC", "compliance"],
            "model": "gpt-4o",
            "tools": ["read_file", "search_code", "search_memory"],
        },
        {
            "key": "qa-lead",
            "name": "QA Lead",
            "designation": "QA Lead",
            "role": "qa_lead",
            "department": "quality_assurance",
            "reports_to": "engineering-manager",
            "goal": "Own migration verification and cutover acceptance testing.",
            "instructions": "Define reconciliation test suites. Gate each phase on a green data-integrity report.",
            "skills": ["QA", "data reconciliation", "test automation"],
            "model": "gpt-4o",
            "tools": ["assign_task", "read_file", "shell_command"],
        },
        {
            "key": "qa-engineer",
            "name": "QA Engineer",
            "designation": "QA Engineer",
            "role": "qa_engineer",
            "department": "quality_assurance",
            "reports_to": "qa-lead",
            "goal": "Execute reconciliation and regression tests each phase.",
            "instructions": "Run row-count and checksum reconciliation. File defects with source/target diffs.",
            "skills": ["test execution", "SQL", "regression testing"],
            "model": "claude-3.5-sonnet",
            "tools": ["read_file", "shell_command", "grep"],
        },
    ]
}
